### ISSUE TITLE
Compile error in VS2015/VS2017

### ISSUE THREAD

**Issue by libaineu2004** [Naios/fluent.cpp#20]
@Naios 

### 
If I use Platform toolset VS2017,Compile error:
\continuable-3.0.0\include\continuable\continuable-types.hpp(54): error C2923: "fu2::function_base": For the parameter "Capacity", "Size" is not valid Template type variable
Continuable-3.0.0\include\continuable\continuable-types.hpp(53): error C2974: 'fu2::function_base' : template is invalid for 'Capacity' and should be type

If I change to use Platform toolset VS2015,Compile error:
Continuable-3.0.0\dep\function2\include\function2\function2.hpp(126): error C2665: "std::forward": None of the 2 overloads can convert all parameter types

### Expected Behavior

{Please write here}

### Actual Behavior

{Please write here}

### Steps to Reproduce

New a win32 console project with Continuable header file：
#include "pch.h"
#include <iostream>
#include <continuable/continuable.hpp>

int main()
{
    std::cout << "Hello World!\n"; 
//auto one = cti::make_ready_continuable(0);
//cti::continuable<int, float, char> three = cti::make_ready_continuable(0, 1.f, '2');
}

### Your Environment

- OS: {Please write here - Windows/Linux dist/OSX}
Win7 x64

- Compiler and version: {Please write here - MSVC/Clang/GCC/Other}
IDE:Visual Studio 2017 (v15.9.13) 
Platform toolset: MSVC2017-x86
Platform toolset: MSVC2015-x86

- Standard library (if non default): {Please write here}
Win32 Console
continuable-3.0.0
function2-4.0.0

**Comment by Naios** [comment]
The MSVC 2017 build works on the [AppVeyor CI](https://ci.appveyor.com/project/Naios/continuable/builds/25284873) works and this issue probably is related to your build environment.


Platform toolset VS2015 is not supported due to the MSVC requirements as stated in the [installation section of the documentation](https://naios.github.io/continuable/installation.html).
```
Visual Studio 2017+ Update 2
Clang 5.0+
GCC 6.0+
```

**Comment by libaineu2004** [comment]
ok, Now I am using the amalgamation header v3.0, it can be compiled normally, thank you!
