### ISSUE TITLE
Continuations are unnecessarily copied

### ISSUE THREAD

**Issue by Inphi** [Naios/fluent.cpp#3]
This happens all the time when making and chaining continuables. It's a bigger problem when continuations have non-empty captures.

**Comment by Naios** [comment]
Thanks for your report.

Could you give a concrete example (or better a concrete unit test)?
The library is designed to use move semantics heavily in order to avoid copies.
However, it is still possible that this isn't working as intended.

**Comment by Inphi** [comment]
it's not an issue. I was unable to reproduce the issue once i created a simple example showing this. In my app, certain objects captured were move inhibited causing the entire continuation to be move inhibited as well.
Sorry for the inconvenience.

**Comment by Naios** [comment]
Maybe you copied the promise, this would cause the whole continuation chain to be copied as well.
In the next major version promises will be move only in order to prevent such issues #2.
