### ISSUE TITLE
Amalgamation for 4.0.0

### ISSUE THREAD

**Issue by Gei0r** [Naios/fluent.cpp#31]
@Naios 

Congratulations on release 4.0.0, the changes look really useful. Get's a feeling of javascript's `Promise` and `async/await` into C++!

Anyway, can you please provide an amalgamation for release 4.0.0 and link it in the documentation?

**Comment by Naios** [comment]
Thanks, I generated a new amalgamation for 4.0.0: https://gist.githubusercontent.com/Naios/25d731aa4707d35a9bcec507f3cb9038/raw/051d2ea07b6704893c7fc9844e8d1c105c6821e0/continuable.hpp

I'm going to link it into the documentation.

**Comment by Naios** [comment]
Just as note: The amalgamation header only contains the headers that require the C+ standard library and function2 which is included as part of the header. The `include/continuable/external/` headers which extend (boost) asio and GTest are not included.

**Comment by Spongman** [comment]
can we get one for `4.1.0` ?

I would also prefer it if the headers used relative includes so it's use was not dependent on a `-I` compiler flag, or env var, eg.:

in `continuable_base.hpp`:
```c++
#include "continuable-primitives.hpp"
#include "continuable-result.hpp"
```

**Comment by Naios** [comment]
If you like, you can create an amalgamation that fits your needs:

I think it uses this tool: https://github.com/edlund/amalgamate

The shell script is located in: `tools/amalgamate/amalgamate.sh`

Simply running this script should be enough to create the header, you can tweak it to fit your needs afterwards.

**Comment by Spongman** [comment]
i have tried doing this, but i can't get it to work. it wowuld be _great_ if someone could post an amalgamation of the most recent release on here.
