### ISSUE TITLE
Continue-on-fail support - allowing chains to continue with a value even after a fail?

### ISSUE THREAD

**Issue by noisypants** [Naios/fluent.cpp#39]
@Naios 
Hello.  Nice work with this library.  it's been fun integrating it into our traditional callback flows.

I am wondering if there's any support to continue-on-fail?  Something similar to `recover` in Scala futures?    Basically handling an exception and allowing the chain to continue with a value or re-throwing the exception for the next `fail `handler to be triggered?  I have use-cases where this is very handy.

https://www.scala-lang.org/api/2.12.3/scala/concurrent/Future.html#recover

thanks.

**Comment by Naios** [comment]
[`cti::recover`](https://naios.github.io/continuable/group___base.html#gacdc6a77a2ff98dabd7a2e9dc8c461934)  and [`cti::rethrow`](https://naios.github.io/continuable/group___base.html#ga9223cf1a04ca2d6950d83d0917192fa5) are fully supported to change the current error state as described in the documentation. Those functions return a [`cti::result`](https://naios.github.io/continuable/classcti_1_1result.html) which can be returned from any handler to change the current error state, either recover from it or introduce an exceptional result:

```cpp
http_request("example.com")
  .then([](std::string content) -> cti::result<int, int> {
    return recover(1, 2);
  })
  .fail([](cti::exception_t exception) -> cti::result<int, int> {
    return recover(1, 2);
  })
  .then([](int a, int b) -> cti::result<int, int> {
    // Recovered from the failure
  })
```

```cpp
http_request("example.com")
  .then([](std::string content) {
    return rethrow(std::make_exception_ptr(std::exception{}));
  })
  .fail([](cti::exception_t exception) {
    return rethrow(std::make_exception_ptr(std::exception{}));
  })
  .next([](auto&&...) {
    return rethrow(std::make_exception_ptr(std::exception{}));
  });
```

**Comment by noisypants** [comment]
awesome!  thanks.  I missed that in the docs.  I will give that a shot.
