### ISSUE TITLE
Example slideshow returns 134

### ISSUE THREAD

**Issue by IceflowRE** [Naios/fluent.cpp#40]
@Naios 

-----

### Commit Hash

6bffb44d2bcca4989945e4d76ce8d35cf8cdcebd / [4.1.0](https://github.com/Naios/continuable/releases/tag/4.1.0)

### Expected Behavior

Return code is 0.

### Actual Behavior

Return error code 134.

### Steps to Reproduce

Execute example [Slideshow](https://github.com/Naios/continuable/blob/master/examples/example-slideshow/example-slideshow.cpp).

### Your Environment

- OS: Linux x86_64
- Compiler and version: Release, gcc 5
- Standard library (if non default): libstdc++11

### Logs
More information and logs [here](https://github.com/conan-io/conan-center-index/pull/2076#issuecomment-765813824)

**Comment by Naios** [comment]
I could not reproduce your issue. Also the slideshow was just created for screenshotting purposes and is not run as part of the regular tests.
Additionally the [documentation](https://naios.github.io/continuable/installation.html) states that GCC 6+ is required by the library.
