### ISSUE TITLE
Tagging a 4.2.1 release?

### ISSUE THREAD

**Issue by nextsilicon-itay-bookstein** [Naios/fluent.cpp#62]
@Naios hi!

We consume the library through conan, and were wondering whether you could tag a 4.2.1 release to include the two minor fixes accumulated since 4.2.0 (the fix to the unsafe_unlocker compilation failure + the clang coroutines detection fix).

I think once a tag is made I could open a PR to include it in https://github.com/conan-io/conan-center-index/blob/master/recipes/continuable/all/conandata.yml .

Thanks for considering!

**Comment by Naios** [comment]
Hey,

sure, I have created a 4.2.1 tag that includes the latest commits:

https://github.com/Naios/continuable/releases/tag/4.2.1

**Comment by nextsilicon-itay-bookstein** [comment]
Thanks! 🙏
