### ISSUE TITLE
CMake files refer to CMAKE_SOURCE_DIR

### ISSUE THREAD

**Issue by HatefulMoron** [Naios/fluent.cpp#7]
@Naios 

-----

Changing the references inside `cmake/configure_macros.cmake` and `cmake/configure_compiler.cmake` from referencing `${CMAKE_SOURCE_DIR}` to `${PROJECT_SOURCE_DIR}` solves this issue for me.

CMAKE_SOURCE_DIR points to the parent project (my project), whereas PROJECT_SOURCE_DIR points to the correct continuable directory.

I'm not completely sure if this is intended, hence I'm creating an issue instead of a pull request.

### Commit Hash

9247e7b85ffbc35eabcd5502a3da6acf0d5261ba

### Expected Behavior

Running 'cmake ..' from the build directory to successfully configure the CMake project

### Actual Behavior

CMake throws errors because it's unable to find:

* ${CMAKE_SOURCE_DIR/}cmake/compiler/*.cmake
* ${CMAKE_SOURCE_DIR}/cmake/macros/group_sources.cmake

### Steps to Reproduce

* Create a directory with a valid CMakeLists.txt with `add_subdirectory(continuable)`
* `git submodule add https://github.com/Naios/continuable.git`
* `git submodule update --init --recursive`
* Create a build directory
* `cmake ..`
```
Produces output similar to:
CMake Error at continuable/cmake/configure_compiler.cmake:29 (include):
  include could not find load file:
    ${CMAKE_SOURCE_DIR}/cmake/compiler/gcc.cmake
Call Stack (most recent call first):
  continuable/cmake/CMakeLists.txt:26 (include)
  continuable/CMakeLists.txt:56 (include)
CMake Error at continuable/cmake/configure_macros.cmake:23 (include):
  include could not find load file:
    ${CMAKE_SOURCE_DIR}/cmake/macros/group_sources.cmake
Call Stack (most recent call first):
  continuable/cmake/CMakeLists.txt:27 (include)
  continuable/CMakeLists.txt:56 (include)
```

### Your Environment

- OS: Linux 4.14.79-1-MANJARO
- Compiler and version: tested both GCC 8.2.1 and clang 7.0.0, cmake 3.12.4
- Standard library (if non default): default

**Comment by Naios** [comment]
Thanks for reporting this issue, could you create a corresponding pull request for it?

**Comment by HatefulMoron** [comment]
Will do, was just checking I wasn't missing something
