### ISSUE TITLE
Question: thread pool of choice

### ISSUE THREAD

**Issue by pfeatherstone** [Naios/fluent.cpp#71]
When using custom executors, is there a good thread pool you recommend that works well with this library or will any be fine ? 

Are task stealing lock free ones a good choice or not ? 

Cheers

**Comment by pfeatherstone** [comment]
I was thinking of benchmarking taskflow vs continuable+thread_pool

**Comment by Naios** [comment]
Hi,
it usually depends on your use-case and requirements what a good thread pool is for you.
The library can be used with all thread pools that support queuing arbitrary callable objects as work.
Therefore, it might be best to benchmark the implementations that fits your use-case.

**Comment by pfeatherstone** [comment]
Okidok. Will have to do some tests.
